### PR TITLE
Gitlab is not using Cucumber anymore

### PR DESCRIPTION
**Pull request by Zaijo**

### CODE REVIEW

**Comment by virajkulkarni14** [comment]
@Zaijo, sorry for the late response. Could please provide a reference for how you found out that Gitlab stopped using Cucumber? If yes, could you please just remove the Gitlab bullet point instead of the entire section? Thanks!

**Comment by Zaijo** [comment]
Because there are no `.feature` files anymore in the repo: https://github.com/gitlabhq/gitlabhq/find/master

**Comment by virajkulkarni14** [comment]
@Zaijo, you're right, they replaced Cucumber with Spinach:
https://github.com/gitlabhq/gitlabhq/commit/9c117f263646635f03b50cac38db4fb830500642
https://github.com/gitlabhq/gitlabhq/commit/3f01ec2d5b7421f05192fc78974a7ff4ba8c8daf
https://github.com/gitlabhq/gitlabhq/commit/bb75052a904c24d1484fa6ec0ad96839effb8ee3
Then they completely moved to Rspec:
https://github.com/gitlabhq/gitlabhq/commit/a78b1b27b86d34c00e1b0631e967d637f8a6714b#diff-9311d51b1b1c450588f3f060a7679393

**Comment by virajkulkarni14** [comment]
@Zaijo, I have now rebased and merged your changes against mine locally, since I've improved the current README. Now closing your PR. Thank you so much and keep contributing!

**Comment by Zaijo** [comment]
The spinach looks good for ruby projects :) Thanks for curating.

**Pull request merged**
